export const NEW_CUSTOM_REQUEST = "NEW_CUSTOM_REQUEST";
export const NEW_CUSTOM_SUCCESS = "NEW_CUSTOM_SUCCESS";
export const NEW_CUSTOM_RESET = "NEW_CUSTOM_RESET";
export const NEW_CUSTOM_FAIL = "NEW_CUSTOM_FAIL";

export const CUSTOM_DETAILS_REQUEST = "CUSTOM_DETAILS_REQUEST";
export const CUSTOM_DETAILS_SUCCESS = "CUSTOM_DETAILS_SUCCESS";
export const CUSTOM_DETAILS_FAIL = "CUSTOM_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";